CREATE DATABASE HOTEL
USE HOTEL

CREATE TABLE RoomTypes(
ID INT PRIMARY KEY IDENTITY,
[TYPES] NVARCHAR(50)
)
INSERT INTO RoomTypes VALUES('Single')
INSERT INTO RoomTypes VALUES('Double')
INSERT INTO RoomTypes VALUES('Triple')
INSERT INTO RoomTypes VALUES('Queen')

CREATE TABLE Rooms(
ID INT PRIMARY KEY IDENTITY,
RoomTypesID INT REFERENCES RoomTypes(ID),
IsReserved BIT DEFAULT(0),
Price INT,
RoomNumber INT,
DescriptionText NVARCHAR(255),
Capacity INT
)
INSERT INTO Rooms VALUES(2,'false',150,22,'2 carpayili otaq',2)
INSERT INTO Rooms VALUES(1,'false',85,34,'1 carpayili otaq',1)
INSERT INTO Rooms VALUES(3,'false',240,41,'3 carpayili otaq',3)
INSERT INTO Rooms VALUES(4,'false',500,50,'boyuk carpayili otaq',2)

CREATE TABLE Customers(
ID INT PRIMARY KEY IDENTITY,
NSF NVARCHAR(255) NOT NULL,      --name,surname,father name
PassportID NVARCHAR(255) UNIQUE NOT NULL,
PHONE NVARCHAR(100) UNIQUE,
EMAIL NVARCHAR(255) UNIQUE,
ADRESS NVARCHAR(255)
)
INSERT INTO Customers VALUES('ELNARA VAHABOVA ELCIN','AZE1234567','(+994)506536687','VAHABOVAELNARA@GMAIL.COM','MEZAHIR RUSTEMOV,26')
INSERT INTO Customers VALUES('NERMIN VAHABOVA ELCIN','AZE1234590','(+994)506536688','VAHABOVANERMIN@GMAIL.COM','MEZAHIR RUSTEMOV,26')
INSERT INTO Customers VALUES('GUNAY MEMMEDOVA ELCIN','AZE1234321','(+994)506536689','MAMMADOVAGUNAY@GMAIL.COM','TBILISI,13')

CREATE TABLE Reservations(
ID INT PRIMARY KEY IDENTITY,
CustomersID INT REFERENCES Customers(ID),
RoomID INT REFERENCES Rooms(ID),
ReservationDATE DATE default GETDATE(),
StartDate DATE default GETDATE(),
EndDATE DATE,
DaysRange int
)
INSERT INTO Reservations VALUES(1,4,'2022-05-12','2022-05-20','2022-05-30',DATEDIFF(DAY,'2022-05-20','2022-05-30'))
INSERT INTO Reservations VALUES(2,3,'2022-06-10','2022-06-20','2022-07-30',DATEDIFF(DAY,'2022-06-20','2022-07-30'))
INSERT INTO Reservations VALUES(3,1,'2022-04-25','2022-05-05','2022-05-20',DATEDIFF(DAY,'2022-05-05','2022-05-20'))

CREATE TABLE PAYMENTSTYPE(
ID INT PRIMARY KEY IDENTITY,
PTYPES NVARCHAR(15) NOT NULL
)
INSERT INTO PAYMENTSTYPE VALUES('BY CARD')
INSERT INTO PAYMENTSTYPE VALUES('BY CASH')

CREATE TABLE PAYMENTS(
ID INT PRIMARY KEY IDENTITY,
CustomerID INT REFERENCES Customers(ID),
ReservationID INT REFERENCES Reservations(ID),
PaymentTypeID INT REFERENCES PAYMENTSTYPE(ID),
TotalPayments INT,
PaymentDATE DATETIME default GETDATE()
)
INSERT INTO PAYMENTS VALUES(1,1,1,1000,'2022-05-12')
INSERT INTO PAYMENTS VALUES(2,2,2,360,'2022-06-10')
INSERT INTO PAYMENTS VALUES(3,3,1,490,'2022-04-25')

CREATE TABLE Spendings(
ID INT PRIMARY KEY IDENTITY,
CustomerID INT REFERENCES Customers(ID),
SpendingsType NVARCHAR(100),
TotalSpendings FLOAT
)
INSERT INTO Spendings VALUES(1,'MEALS',548.65)
INSERT INTO Spendings VALUES(2,'AMUSEMENT',40)
INSERT INTO Spendings VALUES(3,'FOOD',205)

CREATE VIEW GetCustomerDetail
AS
SELECT c.ID,c.NSF,r.DaysRange,r.ReservationDATE FROM Customers AS c
JOIN Reservations AS r
ON c.ID=r.CustomersID

CREATE PROCEDURE GetCustomerSpendings @cost float
AS
SELECT c.NSF, s.TotalSpendings, s.SpendingsType FROM Customers AS c
Join Spendings AS s
ON c.ID=s.CustomerID
WHERE s.TotalSpendings<@cost

EXEC GetCustomerSpendings 500 

CREATE FUNCTION GetCustomerCount (@id int)
RETURNS INT 
AS
BEGIN
	DECLARE @count int
	SELECT @count=COUNT(*) FROM Customers
	WHERE ID>@id
	RETURN @count
END

SELECT [DBO].[GetCustomerCount](2)


SELECT [DBO].[GetCustomerCount]()

CREATE TRIGGER CustomersInsertTrigger
ON Customers
AFTER INSERT
AS
BEGIN
	SELECT * FROM Customers
END

INSERT INTO Customers 
VALUES('AYGUN VAHABOVA XANLAR','AZE1234509','(+994)506536680','VAHABOVAAYGUN@GMAIL.COM','MEZAHIR RUSTEMOV,24')

CREATE TRIGGER CustomerDeleteTrigger
ON Customers
AFTER DELETE
AS 
BEGIN
	SELECT COUNT(*) 'Count Of Customers' FROM Customers
END

DELETE FROM Customers
WHERE ID=3
